/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-105295-g641c4346b3-20220118"
#endif /* AVUTIL_FFVERSION_H */
